name: NPM with yarn.lock diff checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '16.x'

      - name: Install latest npm
        run: npm i -g npm@7

      - name: Build
        run: |
          npm install
          linesChanged=$(git diff | grep -c -e "^\+.+" -e "^\-.+")
          # yarn.lock doesn't store versions, so 0 changes
          if (( linesChanged > 0 )); then
            echo "yarn.lock dependencies were modified externally"
            exit 1
          fi
